#!/bin/bash

file="$1"

error_counter=0
lines=0
for line in $(cat $file)
do
    result=$(echo $line | python main.py)
    [ ! $( echo "$result" | grep Result | grep True) ] && {
        error_counter=$(( $error_counter + 1 ))
        [ ! -z ${SHOW_ERROR_ENTRY+a} ] && {
            echo $result
        }
    }

        lines=$(( $lines + 1 ))
done

echo $(( $error_counter * 100 / $lines ))
